### ISSUE TITLE
<scripture-list> component doesn't expand in Firefox

### ISSUE THREAD

**Issue by spencerwi** [JordanShurmer/web-components#1]
When trying it out in Firefox, I noticed that collapsed passage nodes don't expand when clicked; instead, an error is logged in the JS console from scripture.js line 219 (inside the `_mouseDown(Event)` handler, on the line that checks `event.path[0]`).

The particular error is:

```
TypeError: event.path is undefined
```

Looks like the `path` attribute of `Event` objects is non-standard, and the standardized equivalent is a `composedPath()` getter; see https://stackoverflow.com/questions/39245488/event-path-undefined-with-firefox-and-vue-js

**Comment by JordanShurmer** [comment]
Ah yes, thanks for the Issue. I'll get on this
